sudo: required
language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install -y rpm
  - sudo apt-get install -y -q locales
  - sudo locale-gen es_ES.utf8
rvm:
  - 2.2.4
  - 2.3.0
script:
  - sudo rake test

